### ISSUE TITLE
Possible to add support for the password on the newer NZ series projectors

### ISSUE THREAD

**Issue by bzieroth** [vectronic/homebridge-jvc-projector#5]
Hello,
   I was wondering if you were planning on updating the plug-in to support the required password on the newer NZ models?  I believe the underlying python code you're using has been updated to support this.  Thanks for writing this plug-in!  --Brian

**Comment by vectronic** [comment]
Yes I can do that. Give me a week or so….

**Comment by bzieroth** [comment]
Thank you!

**Comment by vectronic** [comment]
This should be fixed in version 1.3.0 - however my projector doesn't support password so I can't test...

Please note in the `README.md` that the Python module should be installed (re-installed) with this line (to ensure the latest codebase is installed:

`pip install -e git+https://github.com/bezmi/jvc_projector.git#egg=jvc-projector-remote`

**Comment by bzieroth** [comment]
Thanks for your email.  Can confirm that the updated “get_power_state.py” and “set_power_state.py” files work from the command line with the IP and password passed as arguments, but have been unable to get the home bridge plug-in to work in hoobs.  The logs in hoobs just show the projector as being off all the time, doesn’t provide any more detail if it’s seeing an error.  Doesn’t seem like Hoobs (home bridge) is running the files.  Anything I should check?  Thx,  —BDZ

**Comment by vectronic** [comment]
Hmm. You should see something in the Homebridge logs when you toggle the power state due to this line in the plugin:

`log.info('Setting projector power: ' + (newPower ? 'ON': 'OFF'));`
